import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,stat,writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {JournalStore,validDay} from '../../bridge/journal.mjs';
import {createBridge} from '../../bridge/server.mjs';
import {journalDay,journalMarkdown} from '../modules/journal-core.js';
import {readConfig} from '../registry.js';
test('Chicago journal dates cross midnight and daylight saving boundaries',()=>{
  assert.equal(journalDay(new Date('2026-10-07T04:59:59Z')),'2026-10-06');
  assert.equal(journalDay(new Date('2026-10-07T05:00:00Z')),'2026-10-07');
  assert.equal(journalDay(new Date('2026-11-01T07:30:00Z')),'2026-11-01');
  for(const day of ['../secret','2026-02-29','2026-99-01','2026-00-00',null])assert.equal(validDay(day),false);
  assert.equal(validDay('2028-02-29'),true);
});
test('files survive store restart; revisions prevent lost concurrent edits; private mode',async(t)=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'journal-'));t.after(()=>rm(root,{recursive:true,force:true}));
  const store=new JournalStore(root),input={day:'2026-10-06',revision:0,reflection:'<script>literal</script>\nA thought',recap:'Built something'};
  assert.equal((await store.read(input.day)).revision,0);
  const results=await Promise.all([store.save(input),store.save({...input,reflection:'other tab'})]);
  assert.deepEqual(results.map(r=>r.status),[200,409]);
  const reopened=new JournalStore(root),entry=await reopened.read(input.day);assert.equal(entry.reflection,input.reflection);
  assert.equal((await stat(path.join(root,input.day+'.json'))).mode&0o777,0o600);
  assert.deepEqual(await reopened.list(),[input.day]);
  assert.equal((await reopened.save({...input,revision:1,reflection:'edited'})).entry.revision,2);
  assert.equal(JSON.parse(await readFile(path.join(root,input.day+'.json'))).reflection,'edited');
  assert.equal((await reopened.save({...input,day:'../../escape'})).status,400);
  assert.equal((await reopened.save({...input,reflection:'x'.repeat(32001)})).status,400);
  assert.equal((await reopened.save({...input,command:'no'})).status,400);
  const exported=await reopened.export({...input,reflection:'Current unsaved text'});assert.equal(exported.status,200);
  assert.ok((await readFile(exported.path,'utf8')).includes('Current unsaved text'));
  assert.equal((await reopened.read(input.day)).reflection,'edited');
  assert.equal((await stat(exported.path)).mode&0o777,0o600);
  await writeFile(path.join(root,input.day+'.json'),'broken file');
  await assert.rejects(reopened.save({...input,revision:2}));
  assert.equal(await readFile(path.join(root,input.day+'.json'),'utf8'),'broken file');
});
test('journal HTTP shares bridge authorization, bounds input and cannot serve private files',async(t)=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'journal-http-'));t.after(()=>rm(root,{recursive:true,force:true}));
  const journal=new JournalStore(root),bridge=createBridge({journal});const origin=await bridge.listen(0);t.after(()=>new Promise(r=>bridge.server.close(r)));
  const token=(await (await fetch(origin)).text()).match(/name="bridge-token" content="([a-f0-9]+)"/)[1];
  const headers={'Content-Type':'application/json',Origin:origin,'Sec-Fetch-Site':'same-origin','X-Bridge-Token':token};
  const input={day:'2026-10-06',revision:0,reflection:'Private reflection',recap:''};
  for(const override of [{'X-Bridge-Token':'bad'},{Origin:'https://evil.example'},{'Sec-Fetch-Site':'cross-site'}])assert.equal((await fetch(origin+'/api/journal',{method:'POST',headers:{...headers,...override},body:JSON.stringify(input)})).status,403);
  assert.deepEqual(await journal.list(),[]);
  assert.equal((await fetch(origin+'/api/journal',{method:'POST',headers,body:JSON.stringify(input)})).status,200);
  assert.equal((await fetch(origin+'/api/journal',{method:'POST',headers,body:JSON.stringify(input)})).status,409);
  assert.equal((await fetch(origin+'/api/journal/export',{method:'POST',headers,body:JSON.stringify(input)})).status,200);
  assert.equal((await fetch(origin+'/api/journal?day=2026-10-06',{headers})).status,200);
  assert.equal((await fetch(origin+'/api/journal?day=2026-99-01',{headers})).status,400);
  assert.equal((await fetch(origin+'/api/journal?day=2026-10-06&day=2026-10-07',{headers})).status,400);
  assert.equal((await fetch(origin+'/api/journal',{method:'POST',headers,body:'x'.repeat(200001)})).status,413);
  assert.equal((await fetch(origin+'/.journal/2026-10-06.json')).status,404);
});
test('export distinguishes authored notes from unconnected activity and layout persists independently',()=>{
  const text=journalMarkdown({day:'2026-10-06',reflection:'Thinking',recap:'Building'});
  assert.ok(text.includes('written by me'));assert.ok(text.includes('not connected'));assert.ok(text.includes('unsaved draft'));
  const storage={getItem:()=>JSON.stringify({version:1,layout:'journal',backend:'ollama',reflection:'ignore'})};
  assert.deepEqual(readConfig(storage),{version:1,layout:'journal',backend:'ollama'});
});
